% AME60649 Final Project
%This script takes the setup generated by the moltemplate nanotube
%capillary example and selects the sheets/tube

clear all;
close all;

%% load data
load('AME60649_project_final/AME60649_project_final_test01_moltemplate_nanotube.mat');
%contains the variable data where each row corresponds to one atom and
%the columns are those for lammps type full
%atom-ID molecule-ID atom-type q x y z
%q is the charge


z_upper_sheet = 58.26;
z_lower_sheet = 32.0;

%% find atoms
ind_up = data(:,7) == z_upper_sheet;
ind_low = data(:,7) == z_lower_sheet;
ind_tube = data(:,7) < z_upper_sheet & data(:,7) > z_lower_sheet;

%% plot only tube and upper
ind = ind_up;
plot3(data(ind,5),data(ind,6),data(ind,7),'or');
hold on;
ind = ind_tube;
plot3(data(ind,5),data(ind,6),data(ind,7),'ok');
xlabel('x');
ylabel('y');
zlabel('z');
axis equal